# can also run with -fold 1 to get folded spectrum (add this to all angsd commands)
# if running with -fold 1, then the number supplied to realSFS becomes the number of indiv, not the number of chromosomes
/home/ssinghal/bin/angsd0.612/angsd -GL 1 -b /home/ssinghal/encelia/analysis/angsd/ventorum.bamlist.txt -anc /home/ssinghal/encelia/variants/ancestral_allele/ancestral_allele.fa -rf /home/ssinghal/encelia/analysis/angsd/coverage.angsd_regions.txt -P 12 -out /home/ssinghal/encelia/analysis/angsd/ventorum_folded -doSaf 1 -only_proper_pairs 0 -fold 1
/home/ssinghal/bin/angsd0.612/angsd -GL 1 -b /home/ssinghal/encelia/analysis/angsd/palmeri.bamlist.txt -anc /home/ssinghal/encelia/variants/ancestral_allele/ancestral_allele.fa -rf /home/ssinghal/encelia/analysis/angsd/coverage.angsd_regions.txt -P 12 -out /home/ssinghal/encelia/analysis/angsd/palmeri_folded -doSaf 1 -only_proper_pairs 0 -fold 1
/home/ssinghal/bin/angsd0.612/realSFS /home/ssinghal/encelia/analysis/angsd/ventorum_folded.saf 5 -P 12 > /home/ssinghal/encelia/analysis/angsd/ventorum_folded.saf.sfs
/home/ssinghal/bin/angsd0.612/realSFS /home/ssinghal/encelia/analysis/angsd/palmeri_folded.saf 5 -P 12 > /home/ssinghal/encelia/analysis/angsd/palmeri_folded.saf.sfs
gunzip -c /home/ssinghal/encelia/analysis/angsd/ventorum_folded.saf.pos.gz /home/ssinghal/encelia/analysis/angsd/palmeri_folded.saf.pos.gz |sort  -S 50\%|uniq -d|sort -k1,1  -S 50\% > /home/ssinghal/encelia/analysis/angsd/palmeri_ventorum.intersect_sites_folded.txt
/home/ssinghal/bin/angsd0.612/angsd -GL 1 -b /home/ssinghal/encelia/analysis/angsd/ventorum.bamlist.txt -anc /home/ssinghal/encelia/variants/ancestral_allele/ancestral_allele.fa -rf /home/ssinghal/encelia/analysis/angsd/coverage.angsd_regions.txt -P 12 -out /home/ssinghal/encelia/analysis/angsd/ventorum_folded2 -sites /home/ssinghal/encelia/analysis/angsd/palmeri_ventorum.intersect_sites_folded.txt -doSaf 1 -only_proper_pairs 0 -fold 1
/home/ssinghal/bin/angsd0.612/angsd -GL 1 -b /home/ssinghal/encelia/analysis/angsd/palmeri.bamlist.txt -anc /home/ssinghal/encelia/variants/ancestral_allele/ancestral_allele.fa -rf /home/ssinghal/encelia/analysis/angsd/coverage.angsd_regions.txt -P 12 -out /home/ssinghal/encelia/analysis/angsd/palmeri_folded2 -sites /home/ssinghal/encelia/analysis/angsd/palmeri_ventorum.intersect_sites_folded.txt -doSaf 1 -only_proper_pairs 0 -fold 1
/home/ssinghal/bin/angsd0.612/realSFS 2dsfs /home/ssinghal/encelia/analysis/angsd/ventorum_folded2.saf /home/ssinghal/encelia/analysis/angsd/palmeri_folded2.saf 5 5 -P 12 > /home/ssinghal/encelia/analysis/ventorum_palmeri.folded2D.sfs

